import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Countdown from "@/components/countdown/countdown";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased poly-regular `}
      >
        <Countdown targetDate="2025-12-31T23:59:59-05:00"></Countdown>
        {children}
      </body>
    </html>
  );
}
